id = "deer"
display_name = "Venado"

[gompertz]
a = 120.0
b = 0.007
t0 = 120.0

[reproduction]
p_daily = 0.002
sex_ratio = 0.5
offspring_min = 1
offspring_max = 2

[health]
p_sick = 0.005
p_die_if_sick = 0.05

[maturity]
age_days = 365
